# Generated by Django 4.2.30 on 2026-05-08 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_block_block_unique_block_block_prevent_self_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mute',
            constraint=models.UniqueConstraint(fields=('muter', 'muted'), name='unique_mute'),
        ),
        migrations.AddConstraint(
            model_name='mute',
            constraint=models.CheckConstraint(check=models.Q(('muter', models.F('muted')), _negated=True), name='prevent_self_mute'),
        ),
    ]
