# Generated by Django 4.2.30 on 2026-05-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
