# Generated by Django 4.2.30 on 2026-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('follow', 'started following you'), ('mention', 'mentioned you'), ('message', 'sent you a message')], max_length=20),
        ),
    ]
